spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/apisentinel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:apisentinel_user}
    password: ${DB_PASSWORD:apisentinel_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
