import {
  SecurityStatisticsDto,
  SecurityEventDto,
  ApiEndpointDto,
  ApiRequestDto,
  SecurityPolicyDto,
  SimulatorScenario,
} from "@/types";

export const mockStatistics: SecurityStatisticsDto = {
  totalRequests: 14892,
  blockedRequests: 342,
  rateLimitedRequests: 187,
  allowedRequests: 14363,
  totalSecurityEvents: 529,
  averageThreatScore: 43.5,
  eventsBySeverity: {
    LOW: 145,
    MEDIUM: 210,
    HIGH: 118,
    CRITICAL: 56,
  },
  eventsByThreatType: {
    SQL_INJECTION: 198,
    RATE_ABUSE: 142,
    AUTH_ABUSE: 98,
    ENUMERATION: 64,
    SENSITIVE_DATA_EXPOSURE: 27,
  },
  activeBlockedSources: 12,
  recentEvents: [
    {
      id: 101,
      eventId: "e8a93b11-45a2-4cb6-8809-9b16ea9820f1",
      threatType: "SQL_INJECTION",
      severity: "CRITICAL",
      threatScore: 92.0,
      reason: "Boolean-based tautology (' OR 1=1) and UNION SELECT detected in query parameter [search].",
      actionTaken: "BLOCK",
      endpoint: "/api/users/search",
      source: "198.51.100.44",
      evidence: "search=' UNION SELECT password_hash FROM admin_users--",
      timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    },
    {
      id: 102,
      eventId: "a7c290de-3d44-48ee-a0f1-438902beee99",
      threatType: "AUTH_ABUSE",
      severity: "HIGH",
      threatScore: 75.0,
      reason: "Credential stuffing pattern: 48 failed logins within 60s from single IP.",
      actionTaken: "RATE_LIMIT",
      endpoint: "/api/auth/login",
      source: "203.0.113.89",
      evidence: "Failed login count = 48, window = 60s",
      timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    },
    {
      id: 103,
      eventId: "c9284fa0-f19b-4652-9c12-32ba9843cc11",
      threatType: "RATE_ABUSE",
      severity: "HIGH",
      threatScore: 68.0,
      reason: "Request rate exceeded endpoint quota (380 req/min vs 60 allowed).",
      actionTaken: "RATE_LIMIT",
      endpoint: "/api/orders",
      source: "192.0.2.145",
      evidence: "Rate: 380 req/min, burst duration: 45s",
      timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    },
    {
      id: 104,
      eventId: "d192834b-4892-4ec1-9872-47cba6829101",
      threatType: "ENUMERATION",
      severity: "MEDIUM",
      threatScore: 52.0,
      reason: "BOLA/IDOR scan pattern: sequential numeric IDs probed on private resource.",
      actionTaken: "MONITOR",
      endpoint: "/api/customers/{id}",
      source: "198.51.100.12",
      evidence: "IDs scanned: 1042, 1043, 1044, 1045, 1046 within 5s",
      timestamp: new Date(Date.now() - 1000 * 60 * 48).toISOString(),
    },
    {
      id: 105,
      eventId: "b4528109-7a32-4d51-8726-11f87cb5439a",
      threatType: "SENSITIVE_DATA_EXPOSURE",
      severity: "MEDIUM",
      threatScore: 45.0,
      reason: "Unmasked JWT secret and API token reflected in error payload.",
      actionTaken: "WARN",
      endpoint: "/api/integrations/status",
      source: "192.0.2.88",
      evidence: "Response body contained JWT header pattern eyJhbGciOi...",
      timestamp: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    },
  ],
};

export const mockSecurityEvents: SecurityEventDto[] = [
  ...mockStatistics.recentEvents,
  {
    id: 106,
    eventId: "e1029384-9c84-4829-9182-47b2c9842a12",
    threatType: "SQL_INJECTION",
    severity: "HIGH",
    threatScore: 78.0,
    reason: "Stacked SQL query syntax with DROP TABLE attempt detected in POST body.",
    actionTaken: "BLOCK",
    endpoint: "/api/feedback",
    source: "203.0.113.190",
    evidence: "body={\"comment\": \"Great service'; DROP TABLE audit_log;--\"}",
    timestamp: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
  },
  {
    id: 107,
    eventId: "f2938475-8b73-4726-9182-38a7c6195b23",
    threatType: "AUTH_ABUSE",
    severity: "CRITICAL",
    threatScore: 88.0,
    reason: "Brute force password spraying across 12 distinct administrator accounts.",
    actionTaken: "BLOCK",
    endpoint: "/api/auth/token",
    source: "198.51.100.77",
    evidence: "Distinct usernames targeted: 12, window: 90s",
    timestamp: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
  },
  {
    id: 108,
    eventId: "18273645-7a62-4615-9071-29a8b7364c34",
    threatType: "RATE_ABUSE",
    severity: "MEDIUM",
    threatScore: 40.0,
    reason: "Elevated concurrency threshold breached on compute-heavy analytics route.",
    actionTaken: "WARN",
    endpoint: "/api/reports/export",
    source: "192.0.2.204",
    evidence: "Active concurrent workers: 8, threshold: 4",
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 109,
    eventId: "37462819-6b51-4504-8960-18a9c8273d45",
    threatType: "ENUMERATION",
    severity: "LOW",
    threatScore: 22.0,
    reason: "Non-standard probe on deprecated API version /api/v0/metrics.",
    actionTaken: "ALLOW",
    endpoint: "/api/v0/metrics",
    source: "198.51.100.3",
    evidence: "Scanner fingerprint matched Shodan crawler",
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
];

export const mockEndpoints: ApiEndpointDto[] = [
  {
    id: 1,
    pathPattern: "/api/auth/login",
    httpMethod: "POST",
    description: "User authentication & JWT credential issue endpoint",
    sensitivityLevel: "CRITICAL",
    rateLimitPerMinute: 15,
    active: true,
    createdAt: "2026-09-01T00:00:00Z",
    requestCount: 3840,
    threatCount: 98,
    riskScore: 72,
  },
  {
    id: 2,
    pathPattern: "/api/users/**",
    httpMethod: "GET",
    description: "User profile, permissions, and directory operations",
    sensitivityLevel: "HIGH",
    rateLimitPerMinute: 60,
    active: true,
    createdAt: "2026-09-01T00:00:00Z",
    requestCount: 5210,
    threatCount: 45,
    riskScore: 58,
  },
  {
    id: 3,
    pathPattern: "/api/orders/**",
    httpMethod: "POST",
    description: "Checkout, financial transaction, and order placement",
    sensitivityLevel: "CRITICAL",
    rateLimitPerMinute: 30,
    active: true,
    createdAt: "2026-09-01T00:00:00Z",
    requestCount: 1940,
    threatCount: 68,
    riskScore: 84,
  },
  {
    id: 4,
    pathPattern: "/api/products",
    httpMethod: "GET",
    description: "Public catalog browsing and search",
    sensitivityLevel: "LOW",
    rateLimitPerMinute: 300,
    active: true,
    createdAt: "2026-09-01T00:00:00Z",
    requestCount: 9820,
    threatCount: 12,
    riskScore: 18,
  },
  {
    id: 5,
    pathPattern: "/api/admin/**",
    httpMethod: "ANY",
    description: "System administrative console and role management",
    sensitivityLevel: "CRITICAL",
    rateLimitPerMinute: 20,
    active: true,
    createdAt: "2026-09-01T00:00:00Z",
    requestCount: 420,
    threatCount: 54,
    riskScore: 89,
  },
  {
    id: 6,
    pathPattern: "/api/health",
    httpMethod: "GET",
    description: "Infrastructure health status check",
    sensitivityLevel: "LOW",
    rateLimitPerMinute: 120,
    active: true,
    createdAt: "2026-09-01T00:00:00Z",
    requestCount: 14200,
    threatCount: 0,
    riskScore: 0,
  },
];

export const mockRequests: ApiRequestDto[] = [
  {
    id: 201,
    requestId: "req-98437-a1",
    httpMethod: "GET",
    path: "/api/users?search=' UNION SELECT password FROM users--",
    sourceIp: "198.51.100.44",
    userAgent: "sqlmap/1.7#dev",
    responseStatus: 403,
    authStatus: "ANONYMOUS",
    clientIdentifier: "attacker_sqlmap",
    requestSizeBytes: 248,
    responseSizeBytes: 180,
    latencyMs: 14,
    verdict: "BLOCKED",
    threatScore: 92.0,
    timestamp: new Date(Date.now() - 1000 * 20).toISOString(),
  },
  {
    id: 202,
    requestId: "req-98438-b2",
    httpMethod: "POST",
    path: "/api/auth/login",
    sourceIp: "203.0.113.89",
    userAgent: "python-requests/2.31.0",
    responseStatus: 429,
    authStatus: "FAILED",
    clientIdentifier: "bot_stuffing",
    requestSizeBytes: 420,
    responseSizeBytes: 210,
    latencyMs: 8,
    verdict: "RATE_LIMITED",
    threatScore: 75.0,
    timestamp: new Date(Date.now() - 1000 * 45).toISOString(),
  },
  {
    id: 203,
    requestId: "req-98439-c3",
    httpMethod: "GET",
    path: "/api/products",
    sourceIp: "66.249.66.1",
    userAgent: "Mozilla/5.0 (compatible; Googlebot/2.1)",
    responseStatus: 200,
    authStatus: "ANONYMOUS",
    clientIdentifier: "crawler_google",
    requestSizeBytes: 110,
    responseSizeBytes: 8900,
    latencyMs: 32,
    verdict: "ALLOWED",
    threatScore: 0.0,
    timestamp: new Date(Date.now() - 1000 * 90).toISOString(),
  },
  {
    id: 204,
    requestId: "req-98440-d4",
    httpMethod: "GET",
    path: "/api/customers/1043",
    sourceIp: "198.51.100.12",
    userAgent: "BurpSuitePro/2024.1",
    responseStatus: 200,
    authStatus: "AUTHENTICATED",
    clientIdentifier: "corp_user_42",
    requestSizeBytes: 310,
    responseSizeBytes: 1420,
    latencyMs: 24,
    verdict: "MONITORED",
    threatScore: 52.0,
    timestamp: new Date(Date.now() - 1000 * 150).toISOString(),
  },
  {
    id: 205,
    requestId: "req-98441-e5",
    httpMethod: "POST",
    path: "/api/orders",
    sourceIp: "192.0.2.145",
    userAgent: "Go-http-client/1.1",
    responseStatus: 429,
    authStatus: "AUTHENTICATED",
    clientIdentifier: "partner_api_key",
    requestSizeBytes: 840,
    responseSizeBytes: 190,
    latencyMs: 11,
    verdict: "RATE_LIMITED",
    threatScore: 68.0,
    timestamp: new Date(Date.now() - 1000 * 220).toISOString(),
  },
  {
    id: 206,
    requestId: "req-98442-f6",
    httpMethod: "GET",
    path: "/api/security/statistics",
    sourceIp: "127.0.0.1",
    userAgent: "NextJS-Dashboard-Client",
    responseStatus: 200,
    authStatus: "AUTHENTICATED",
    clientIdentifier: "admin_soc",
    requestSizeBytes: 95,
    responseSizeBytes: 2400,
    latencyMs: 9,
    verdict: "ALLOWED",
    threatScore: 0.0,
    timestamp: new Date(Date.now() - 1000 * 290).toISOString(),
  },
];

export const mockPolicies: SecurityPolicyDto[] = [
  {
    id: 1,
    name: "Default Perimeter Guard",
    description: "Global fallback threat threshold for all incoming API endpoints",
    pathPattern: "/**",
    threatScoreThreshold: 80,
    action: "BLOCK",
    rateLimitPerMinute: 300,
    active: true,
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-05T09:00:00Z",
  },
  {
    id: 2,
    name: "Authentication Shield",
    description: "Strict anti-brute force and credential abuse policy for auth routes",
    pathPattern: "/api/auth/**",
    threatScoreThreshold: 60,
    action: "RATE_LIMIT",
    rateLimitPerMinute: 20,
    active: true,
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-05T09:00:00Z",
  },
  {
    id: 3,
    name: "Admin Console Zero-Trust",
    description: "Aggressive block on any injection or privilege escalation anomaly",
    pathPattern: "/api/admin/**",
    threatScoreThreshold: 50,
    action: "BLOCK",
    rateLimitPerMinute: 30,
    active: true,
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-05T09:00:00Z",
  },
  {
    id: 4,
    name: "Orders & Financial Gateway",
    description: "Monitors transactions for rapid automated order placement",
    pathPattern: "/api/orders/**",
    threatScoreThreshold: 70,
    action: "WARN",
    rateLimitPerMinute: 45,
    active: true,
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-05T09:00:00Z",
  },
];

export const mockAttackScenarios: SimulatorScenario[] = [
  {
    id: "sqli-tautology",
    name: "SQL Injection: Tautology Bypass",
    threatType: "SQL_INJECTION",
    description: "Exploits boolean conditions (' OR 1=1--) to extract unauthorized data.",
    defaultEndpoint: "/api/security/events?search=%27%20OR%201=1--",
    defaultMethod: "GET",
    samplePayload: "search=' OR 1=1--",
    expectedSeverity: "MEDIUM",
  },
  {
    id: "sqli-union",
    name: "SQL Injection: UNION Extraction",
    threatType: "SQL_INJECTION",
    description: "Attempts multi-table extraction with UNION SELECT syntax.",
    defaultEndpoint: "/api/security/events?search=%27%20UNION%20SELECT%20username,password%20FROM%20users--",
    defaultMethod: "GET",
    samplePayload: "search=' UNION SELECT username,password FROM users--",
    expectedSeverity: "CRITICAL",
  },
  {
    id: "auth-bruteforce",
    name: "Authentication Brute Force",
    threatType: "AUTH_ABUSE",
    description: "Simulates high-velocity invalid login attempts with bad credentials.",
    defaultEndpoint: "/api/auth/login",
    defaultMethod: "POST",
    samplePayload: "{\"username\": \"admin\", \"password\": \"wrong_pass_test\"}",
    expectedSeverity: "HIGH",
  },
  {
    id: "rate-abuse-burst",
    name: "High-Frequency Rate Abuse Burst",
    threatType: "RATE_ABUSE",
    description: "Floods the target endpoint with rapid-fire requests exceeding quota.",
    defaultEndpoint: "/api/requests",
    defaultMethod: "GET",
    samplePayload: "",
    expectedSeverity: "HIGH",
  },
  {
    id: "enumeration-bola",
    name: "Object Identifier Enumeration (BOLA)",
    threatType: "ENUMERATION",
    description: "Iterates sequential resource identifiers to discover unauthorized records.",
    defaultEndpoint: "/api/endpoints/{id}",
    defaultMethod: "GET",
    samplePayload: "Iterating IDs 1, 2, 3, 4, 5, 9999",
    expectedSeverity: "MEDIUM",
  },
  {
    id: "benign-baseline",
    name: "Legitimate Baseline Traffic",
    threatType: "NONE",
    description: "Normal, authorized API requests to verify low false-positive rate.",
    defaultEndpoint: "/api/health",
    defaultMethod: "GET",
    samplePayload: "",
    expectedSeverity: "LOW",
  },
];
